@startmindmap Map
* D&D 5E
 * Character
  * Race
   * Abliity Score Increase
   * Alignment
   * Size
   * Speed
   * Races
    * Dwarf
    * Elf
    * Halfling
    *[#LightGreen] Human
    * Dragonborn
    * Gnome
    * Half-Elf
    * Half-Orc
    * Tiefling
   * Subraces
  * Class
   * Class Features
   * Proficiencies
   * Classes
    * Barbarian
    * Bard
    * Cleric
    * Druid
    * Fighter
    * Monk
    * Paladin
    * Ranger
    * Rogue
    * Sorcerer
    * Warlock
    * Wizard
  * Level
  * Hit Points and Hit Dice
  * Proficiency Bonus
  * Ability Scores
   * Ablities
    * Strength
    * Dexterity
    * Constitution
    * Intelligence
    * Wisdom
    * Charisma
   * Ability Modifier
   * Ability Score Point Cost
  * Equipment
   * Armor Class
   * Weapons
    * Melee Weapons
    * Ranged Weapons


@end