#application: zxnn-hrd
#version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css/
  static_dir: static/css
  expiration: "7d"

- url: /script/
  static_dir: static/script
  expiration: "7d"

- url: /img/
  static_dir: static/img
  expiration: "7d"

- url: /
  script: zxnn.gae.main.app

- url: /index\.html
  script: zxnn.gae.main.app

- url: /dashboard/.*
  script: zxnn.gae.dashboard.app
  login: required
  auth_fail_action: unauthorized

- url: /upload_avatar
  script: zxnn.gae.dashboard.app

- url: /public/avatar
  script: zxnn.gae.dashboard.app

- url: /todone/.*
  script: zxnn.gae.todone.app
  login: required

- url: /ilog/.*
  script: zxnn.gae.ilog.app

- url: /wow/.*
  script: zxnn.gae.wow.app

- url: /tools/.*
  script: zxnn.gae.tools.app
