application: zxnn-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: main.app

- url: /index\.html
  script: main.py

- url: /css/
  static_dir: static/css

- url: /script/
  static_dir: static/script

- url: /img/
  static_dir: static/img

- url: /dashboard/.*
  script: bd.app

- url: /public/\w+/avatar
  script: bd.py

- url: /todone/.*
  script: todone.py

- url: /countdown/.*
  script: countdown.py

- url: /tester/.*
  script: tester.py

- url: /ilog/.*
  script: ilog.app
