application: zxnn-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css/
  static_dir: static/css
  expiration: "7d"

- url: /script/
  static_dir: static/script
  expiration: "7d"

- url: /img/
  static_dir: static/img
  expiration: "7d"

- url: /
  script: main.app

- url: /index\.html
  script: main.app

- url: /dashboard/.*
  script: bd.app
  login: required
  auth_fail_action: unauthorized

- url: /public/\w+/avatar
  script: bd.app

- url: /todone/.*
  script: todone.py
  login: required

- url: /countdown/.*
  script: countdown.py
  login: required

- url: /tester/.*
  script: tester.py
  login: required

- url: /ilog/.*
  script: ilog.app
