application: zxnn
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /index\.html
  script: main.py

- url: /css/
  static_dir: static/css

- url: /script/
  static_dir: static/script

- url: /img/
  static_dir: static/img

- url: /dashboard/.*
  script: bd.py

- url: /todone/.*
  script: todone.py

- url: /countdown/.*
  script: countdown.py

- url: /tester/.*
  script: tester.py

- url: /ilog/.*
  script: ilog.py
